_BASE_: "base.yaml"

TASK: "classification"

MODEL:
  NAME: "biovil_t_classification"
  DROPOUT: 0.1
  FUSED_DIM: 2176
  NUM_CLASSES: 5

SOLVER:
  NUM_EPOCHS: 18
  BATCH_SIZE: 32 # Paper uses 32, but T4 may OOM. Use 32, or 8 w/ gradient_accumulation=4
  GRADIENT_CLIP: 0.1

OUTPUT_DIR: "./output/biovil_t_classification"
