_BASE_: "base.yaml"

TASK: "classification"

MODEL:
  NAME: "resnet_lstm_classification"
  EMBED_DIM: 300
  LSTM_HIDDEN_DIM: 512
  DROPOUT: 0.1
  NUM_CLASSES: 5

SOLVER:
  NUM_EPOCHS: 25
  BATCH_SIZE: 32
  GRADIENT_CLIP: 0.1

OUTPUT_DIR: "./output/resnet_lstm_classification"
