_BASE_: "base.yaml"

TASK: "generation"

MODEL:
  NAME: "resnet_lstm_generation"
  EMBED_DIM: 300
  LSTM_HIDDEN_DIM: 512
  ATTENTION_DIM: 256
  ENCODER_DIM: 2048 
  DROPOUT: 0.1

SOLVER:
  NUM_EPOCHS: 25
  BATCH_SIZE: 32
  GRADIENT_CLIP: 0.1

OUTPUT_DIR: "./output/resnet_lstm_generation"
