_BASE_: "base.yaml"

TASK: "classification"

MODEL:
  NAME: "biovil_t_classification"
  DROPOUT: 0.1
  FUSED_DIM: 2176
  NUM_CLASSES: 5

SOLVER:
  NUM_EPOCHS: 18
  BATCH_SIZE: 32
  GRADIENT_CLIP: 0.1

OUTPUT_DIR: "./output/biovil_t_classification"
